name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        # fetch all tags for dynamic versioning
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # try poetry install to test if it works
      - name: Install Poetry and installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install